version: "3"

services:
  top-video-generator:
    container_name: top-video-generator
    image: top-video-generator:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    env_file:
      - ./docker-environment.env
