version: "3"

services:
  top-video-generator:
    image: top-video-generator
    ports:
      - "8080:8080"
    cpus: 1.5
    mem_limit: 2500M
    mem_reservation: 128M
    volumes:
      - ./prod:/app/db
      - ./prod/videos:/app/videos
      - ./prod/yt_client_secret.json:/app/yt_client_secret.json
      - ./prod/logs:/app/logs
    env_file:
      - ./docker-environment.env
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 2500M
        reservations:
          cpus: '0.2'
          memory: 128M
