services:
  top-video-generator:
    image: top-video-generator
    ports:
      - "8080:8080"
    volumes:
      - ./prod:/app/db
      - ./prod/videos:/app/videos
      - ./prod/yt_client_secret.json:/app/yt_client_secret.json
      - ./prod/instagram_session.json:/app/instagram_session.json
      - ./prod/logs:/app/logs
    env_file:
      - ./docker-environment.env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2500M
        reservations:
          cpus: '0.15'
          memory: 64M
