services:
  top-video-generator:
    container_name: top-video-generator
    image: ${TOP_VIDEO_GENERATOR_IMAGE:-top-video-generator:latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false
